# Importing Libraries

In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


# Preprocessing Data set

* Importing dataset

In [18]:
cleveland_dataset = pd.read_csv('cleveland_kaggle.csv')

* Seprating target column from Features

In [19]:
X = cleveland_dataset.iloc[:, :-1].values
y = cleveland_dataset.iloc[:, -1].values

* Splitting to Train and Test dataset

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

* Feature Scaling

In [21]:
print(X_train)

[[43.  0.  2. ...  1.  0.  2.]
 [66.  0.  2. ...  1.  1.  2.]
 [58.  1.  2. ...  2.  0.  2.]
 ...
 [56.  1.  3. ...  1.  0.  3.]
 [47.  1.  2. ...  2.  0.  2.]
 [58.  1.  1. ...  1.  0.  2.]]
